<?php

declare(strict_types=1);

namespace App\Models\Delivery;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A concrete tour run for a specific date.
 *
 * Generated by TourPlannerService::createTourForDate() from a
 * RegularDeliveryTour template and a calendar date.
 *
 * Status lifecycle:
 *   planned → in_progress → done
 *          ↘ cancelled (from any state before done)
 *
 * driver_employee_id is stored as a plain bigint — no FK constraint because
 * the Employee module does not yet exist in this schema.
 *
 * @property int              $id
 * @property \Carbon\Carbon   $tour_date
 * @property int|null         $regular_delivery_tour_id
 * @property int|null         $driver_employee_id
 * @property string           $status
 * @property \Carbon\Carbon   $created_at
 * @property \Carbon\Carbon   $updated_at
 *
 * @property-read RegularDeliveryTour|null  $regularDeliveryTour
 * @property-read Collection<int, TourStop> $stops
 */
class Tour extends Model
{
    public const STATUS_PLANNED     = 'planned';
    public const STATUS_IN_PROGRESS = 'in_progress';
    public const STATUS_DONE        = 'done';
    public const STATUS_CANCELLED   = 'cancelled';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'tour_date',
        'regular_delivery_tour_id',
        'driver_employee_id',
        'status',
        'started_at',
        'ended_at',
    ];

    /**
     * @var array<string, string>
     */
    protected $casts = [
        'tour_date'  => 'date',
        'started_at' => 'datetime',
        'ended_at'   => 'datetime',
    ];

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    /**
     * The recurring template this tour was generated from.
     */
    public function regularDeliveryTour(): BelongsTo
    {
        return $this->belongsTo(RegularDeliveryTour::class);
    }

    /**
     * All stops (customer deliveries) on this tour, ordered by stop_index.
     *
     * @return HasMany<TourStop>
     */
    public function stops(): HasMany
    {
        return $this->hasMany(TourStop::class)->orderBy('stop_index');
    }
}
