<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Upload jobs created offline, synced later.
 *
 * Lifecycle:
 *   1. Client creates upload_requested driver_event with client_upload_id.
 *   2. Server creates driver_uploads row with status=pending.
 *   3. When client comes online it POSTs the file to /api/driver/upload.
 *   4. Server stores file, sets status=uploaded and file_path.
 *
 * Idempotent by (device_id, client_upload_id).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('driver_uploads', function (Blueprint $table) {
            $table->bigIncrements('id');

            // Driver identity
            $table->unsignedBigInteger('employee_id')->nullable();
            $table->string('device_id');
            $table->string('client_upload_id')->comment('UUID generated by client; idempotency key');

            // Domain references (no FK constraints)
            $table->unsignedBigInteger('tour_stop_id')->nullable();
            $table->unsignedBigInteger('order_id')->nullable();

            // Upload metadata
            $table->string('upload_type')->comment('proof_of_delivery|delivery_note|other');
            $table->string('file_path')->nullable()->comment('Relative to storage/app');
            $table->string('mime_type')->nullable();
            $table->string('original_name')->nullable();
            $table->unsignedInteger('file_size')->nullable()->comment('Bytes');

            // Status
            $table->string('status')->default('pending')
                ->comment('pending|uploaded|failed');

            $table->timestamps();

            // Idempotency key
            $table->unique(['device_id', 'client_upload_id'], 'driver_uploads_device_client_unique');

            // Query indexes
            $table->index(['tour_stop_id', 'status'], 'driver_uploads_stop_status_idx');
            $table->index('employee_id', 'driver_uploads_employee_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('driver_uploads');
    }
};
