<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Append-only driver event log.
 *
 * Idempotent by (device_id, client_event_id). The server side must silently
 * skip any event whose (device_id, client_event_id) pair already exists.
 *
 * apply_status lifecycle:
 *   pending → applied   (domain logic succeeded)
 *   pending → rejected  (validation or domain error; see apply_error)
 *
 * All foreign-key columns (tour_id, tour_stop_id, order_id, order_item_id,
 * employee_id) are stored without DB-level FK constraints so that partial
 * data or future module additions do not break old event rows.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('driver_events', function (Blueprint $table) {
            $table->bigIncrements('id');

            // Driver identity
            $table->unsignedBigInteger('employee_id')->nullable();
            $table->string('device_id')->comment('Stable device UUID, generated on first app open');
            $table->string('client_event_id')->comment('UUID generated by client per event; idempotency key');

            // Event classification
            $table->string('event_type')->comment(
                'arrived|finished|item_delivered|item_not_delivered|payment|'
                . 'empties_adjustment|breakage_adjustment|note|upload_requested'
            );

            // Domain references (no FK constraints)
            $table->unsignedBigInteger('tour_id')->nullable();
            $table->unsignedBigInteger('tour_stop_id')->nullable();
            $table->unsignedBigInteger('order_id')->nullable();
            $table->unsignedBigInteger('order_item_id')->nullable();

            // Arbitrary event payload
            $table->json('payload_json')->nullable();

            // Timing
            $table->dateTime('received_at');
            $table->dateTime('applied_at')->nullable();

            // Processing status
            $table->string('apply_status')->default('pending')
                ->comment('pending|applied|rejected');
            $table->text('apply_error')->nullable();

            // Idempotency key: one event per (device, client UUID)
            $table->unique(['device_id', 'client_event_id'], 'driver_events_device_client_unique');

            // Query indexes
            $table->index(['tour_stop_id', 'event_type'], 'driver_events_stop_type_idx');
            $table->index('order_id', 'driver_events_order_idx');
            $table->index('employee_id', 'driver_events_employee_idx');
            $table->index('apply_status', 'driver_events_status_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('driver_events');
    }
};
