<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Addresses sourced from:
     * - wawi_dbo_tlieferant (12 direct matches)
     * - Official company Impressum pages (remainder)
     */
    public function up(): void
    {
        $brands = [
            // ── Wawi-Lieferant matches ──────────────────────────────────────────
            'Ayinger Brauhaus' => [
                'adresse' => 'Zornedinger Straße 1',
                'plz'     => '85653',
                'ort'     => 'Aying',
                'land'    => 'Deutschland',
                'website' => 'www.ayinger.de',
            ],
            'Baikal Getränke' => [
                'adresse' => 'Am Tempelhofer Berg 6',
                'plz'     => '10965',
                'ort'     => 'Berlin',
                'land'    => 'Deutschland',
                'email'   => 'order@wostok-limonade.de',
            ],
            'Brauhaus Faust KG' => [
                'adresse' => 'Hauptstraße 219',
                'plz'     => '63897',
                'ort'     => 'Miltenberg',
                'land'    => 'Deutschland',
                'email'   => 'versand@faust.de',
                'website' => 'www.faust.de',
            ],
            'Hassia Mineralquellen' => [
                'adresse' => 'Gießener Straße 18-30',
                'plz'     => '61118',
                'ort'     => 'Bad Vilbel',
                'land'    => 'Deutschland',
                'email'   => 'bestellannahme@hassia-gruppe.com',
                'website' => 'www.hassia.com',
            ],
            'Herrnbräu' => [
                'adresse' => 'Manchinger Straße 95',
                'plz'     => '85053',
                'ort'     => 'Ingolstadt',
                'land'    => 'Deutschland',
                'website' => 'www.herrnbraeu.de',
            ],
            'Kelterei Dölp' => [
                'adresse' => 'Otzbergstraße 16',
                'plz'     => '64395',
                'ort'     => 'Brensbach',
                'land'    => 'Deutschland',
                'email'   => 'bestellung@kelterei-doelp.de',
                'website' => 'www.kelterei-doelp.de',
            ],
            'Kelterei Krämer GmbH' => [
                'adresse' => 'Crumbacher Straße 6',
                'plz'     => '64385',
                'ort'     => 'Reichelsheim',
                'land'    => 'Deutschland',
                'email'   => 'info@kelterei-kraemer.de',
                'website' => 'www.kelterei-kraemer.de',
            ],
            'Pfungstädter Brauerei' => [
                'adresse' => 'Eberstädter Straße 89',
                'plz'     => '64319',
                'ort'     => 'Pfungstadt',
                'land'    => 'Deutschland',
                'email'   => 'Bestellung@pfungstaedter.de',
                'website' => 'www.pfungstaedter.de',
            ],
            'Piranjasoul GmbH' => [
                'adresse' => 'Wellesweilerstraße 69b',
                'plz'     => '66538',
                'ort'     => 'Neunkirchen',
                'land'    => 'Deutschland',
                'website' => 'www.piranja-cola.de',
            ],
            'Rapps' => [
                'adresse' => 'Gießener Straße 18-30',
                'plz'     => '61118',
                'ort'     => 'Bad Vilbel',
                'land'    => 'Deutschland',
                'email'   => 'bestellannahme@hassia-gruppe.com',
                'website' => 'www.rapps.de',
            ],
            'Schmucker Brauerei GmbH' => [
                'adresse' => 'Hauptstraße 89',
                'plz'     => '64756',
                'ort'     => 'Mossautal',
                'land'    => 'Deutschland',
                'email'   => 'bierbestellung@schmucker-bier.de',
                'website' => 'www.schmucker-bier.de',
            ],
            'Vivaris Getränke Verwaltung GmbH' => [
                'adresse' => 'Neuer Grund 24',
                'plz'     => '49740',
                'ort'     => 'Haselünne',
                'land'    => 'Deutschland',
                'website' => 'www.vivaris.net',
            ],

            // ── Impressum-Recherche ─────────────────────────────────────────────
            'ABinBev' => [
                'adresse' => 'Am Deich 18/19',
                'plz'     => '28199',
                'ort'     => 'Bremen',
                'land'    => 'Deutschland',
                'website' => 'www.ab-inbev.de',
            ],
            'Adelholzner' => [
                'adresse' => 'St.-Primus-Straße 1-5',
                'plz'     => '83313',
                'ort'     => 'Siegsdorf',
                'land'    => 'Deutschland',
                'website' => 'www.adelholzener.de',
            ],
            'Afri Cola' => [
                'adresse' => 'Badstraße 41',
                'plz'     => '75385',
                'ort'     => 'Bad Teinach-Zavelstein',
                'land'    => 'Deutschland',
                'website' => 'www.afri-cola.de',
            ],
            'Almdudler' => [
                'adresse' => 'Grinzinger Allee 16',
                'plz'     => '1190',
                'ort'     => 'Wien',
                'land'    => 'Österreich',
                'website' => 'www.almdudler.com',
            ],
            'Alwa' => [
                'adresse' => 'Am Hauptbahnhof 18',
                'plz'     => '60329',
                'ort'     => 'Frankfurt am Main',
                'land'    => 'Deutschland',
                'website' => 'www.alwa-mineralwasser.de',
            ],
            'Augustinerbraeu' => [
                'adresse' => 'Landsberger Straße 31-35',
                'plz'     => '80339',
                'ort'     => 'München',
                'land'    => 'Deutschland',
                'website' => 'www.augustiner-braeu.de',
            ],
            'Bionade' => [
                'adresse' => 'Nordheimer Straße 14',
                'plz'     => '97645',
                'ort'     => 'Ostheim vor der Rhön',
                'land'    => 'Deutschland',
                'email'   => 'info@bionade.de',
                'website' => 'www.bionade.de',
            ],
            'Bitburger' => [
                'adresse' => 'Römermauer 3',
                'plz'     => '54634',
                'ort'     => 'Bitburg',
                'land'    => 'Deutschland',
                'website' => 'www.bitburger.de',
            ],
            'Black forest' => [
                'adresse' => 'Äußerer Vogelsberg 7',
                'plz'     => '72290',
                'ort'     => 'Loßburg',
                'land'    => 'Deutschland',
                'website' => 'www.blackforest-water.com',
            ],
            'Bluna' => [
                'adresse' => 'Badstraße 41',
                'plz'     => '75385',
                'ort'     => 'Bad Teinach-Zavelstein',
                'land'    => 'Deutschland',
                'website' => 'www.bluna.de',
            ],
            'Brauerei Riegele' => [
                'adresse' => 'Frölichstraße 26',
                'plz'     => '86150',
                'ort'     => 'Augsburg',
                'land'    => 'Deutschland',
                'website' => 'www.riegele.de',
            ],
            'Burkhardt Fruchtsäfte GmbH & Co. KG' => [
                'adresse' => 'Steiglesstraße 10',
                'plz'     => '89150',
                'ort'     => 'Laichingen',
                'land'    => 'Deutschland',
                'website' => 'www.burkhardt-fruchtsaefte.de',
            ],
            'Campari' => [
                'adresse' => 'Adelgundenstraße 7',
                'plz'     => '80538',
                'ort'     => 'München',
                'land'    => 'Deutschland',
                'website' => 'www.campari.com',
            ],
            'Carlsberg Deutschland GmbH' => [
                'adresse' => 'Jürgen-Töpfer-Straße 50',
                'plz'     => '22763',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'website' => 'www.carlsberg.de',
            ],
            'Chiemseer' => [
                'adresse' => 'Schlosshof 2',
                'plz'     => '83371',
                'ort'     => 'Stein an der Traun',
                'land'    => 'Deutschland',
                'website' => 'www.steiner-bier.de',
            ],
            'Coca Cola' => [
                'adresse' => 'Stralauer Allee 4',
                'plz'     => '10245',
                'ort'     => 'Berlin',
                'land'    => 'Deutschland',
                'website' => 'www.coca-cola.com/de/de',
            ],
            'Darmstädter Brauerei' => [
                'adresse' => 'Goebelstraße 7',
                'plz'     => '64293',
                'ort'     => 'Darmstadt',
                'land'    => 'Deutschland',
                'website' => 'www.darmstaedter.de',
            ],
            'Diageo' => [
                'adresse' => 'Reeperbahn 1',
                'plz'     => '20359',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'website' => 'www.diageo.com',
            ],
            'Eders & Heylands Brauerei' => [
                'adresse' => 'Aschaffenburger Straße 3-5',
                'plz'     => '63762',
                'ort'     => 'Großostheim',
                'land'    => 'Deutschland',
                'website' => 'www.eders.de',
            ],
            'Eichbaum' => [
                'adresse' => 'Käfertaler Straße 170',
                'plz'     => '68167',
                'ort'     => 'Mannheim',
                'land'    => 'Deutschland',
                'website' => 'www.eichbaum.de',
            ],
            'Erdinger' => [
                'adresse' => 'Lange Zeile 1+3',
                'plz'     => '85435',
                'ort'     => 'Erding',
                'land'    => 'Deutschland',
                'email'   => 'info@erdinger.de',
                'website' => 'www.erdinger.de',
            ],
            'Flensburger' => [
                'adresse' => 'Munketoft 12',
                'plz'     => '24937',
                'ort'     => 'Flensburg',
                'land'    => 'Deutschland',
                'website' => 'www.flens.de',
            ],
            'Flora Power' => [
                'adresse' => 'Am Römergut 7',
                'plz'     => '86853',
                'ort'     => 'Langerringen',
                'land'    => 'Deutschland',
                'website' => 'www.florapower.de',
            ],
            'Fritz Kola' => [
                'adresse' => 'Spaldingstraße 64-68',
                'plz'     => '20097',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'email'   => 'info@fritz-kola.de',
                'website' => 'www.fritz-kola.de',
            ],
            'Frueh Koelsch' => [
                'adresse' => 'Am Hof 12-18',
                'plz'     => '50667',
                'ort'     => 'Köln',
                'land'    => 'Deutschland',
                'website' => 'www.frueh.de',
            ],
            'Gaffel' => [
                'adresse' => 'Welserstraße 16',
                'plz'     => '51149',
                'ort'     => 'Köln',
                'land'    => 'Deutschland',
                'website' => 'www.gaffel.de',
            ],
            'Gerolsteiner Brunnen GmbH & Co. KG' => [
                'adresse' => 'Raderbergstraße 2',
                'plz'     => '54568',
                'ort'     => 'Gerolstein',
                'land'    => 'Deutschland',
                'website' => 'www.gerolsteiner.de',
            ],
            'Gorbatschow' => [
                'adresse' => 'Biebricher Allee 142',
                'plz'     => '65187',
                'ort'     => 'Wiesbaden',
                'land'    => 'Deutschland',
                'website' => 'www.henkell-freixenet.com',
            ],
            'Grohe' => [
                'adresse' => 'Nieder-Ramstädter Straße 3',
                'plz'     => '64283',
                'ort'     => 'Darmstadt',
                'land'    => 'Deutschland',
                'website' => 'www.brauerei-grohe.de',
            ],
            'Guiness' => [
                'adresse' => 'St. James\'s Gate',
                'plz'     => 'D08 VF8H',
                'ort'     => 'Dublin',
                'land'    => 'Irland',
                'website' => 'www.guinness.com',
            ],
            'Hansa' => [
                'adresse' => 'Doberaner Straße 27',
                'plz'     => '18057',
                'ort'     => 'Rostock',
                'land'    => 'Deutschland',
                'website' => 'www.rostocker.de',
            ],
            'Heineken' => [
                'adresse' => 'Ehrenbergstraße 19',
                'plz'     => '10245',
                'ort'     => 'Berlin',
                'land'    => 'Deutschland',
                'website' => 'www.heineken.com/de/de',
            ],
            'Jack daniels' => [
                'adresse' => 'Dammtorwall 7',
                'plz'     => '20354',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'website' => 'www.brown-forman.de',
            ],
            'Jaegermeister' => [
                'adresse' => 'Jägermeisterstraße 7-15',
                'plz'     => '38302',
                'ort'     => 'Wolfenbüttel',
                'land'    => 'Deutschland',
                'website' => 'www.mast-jaegermeister.de',
            ],
            'Jever' => [
                'adresse' => 'Elisabethufer 18',
                'plz'     => '26441',
                'ort'     => 'Jever',
                'land'    => 'Deutschland',
                'website' => 'www.jever.de',
            ],
            'Köstritzer' => [
                'adresse' => 'Heinrich-Schütz-Straße 16',
                'plz'     => '07586',
                'ort'     => 'Bad Köstritz',
                'land'    => 'Deutschland',
                'website' => 'www.koestritzer.de',
            ],
            'Krombacher' => [
                'adresse' => 'Hagener Straße 261',
                'plz'     => '57223',
                'ort'     => 'Kreuztal',
                'land'    => 'Deutschland',
                'website' => 'www.krombacher.de',
            ],
            'lammsbraeu' => [
                'adresse' => 'Amberger Straße 1',
                'plz'     => '92318',
                'ort'     => 'Neumarkt in der Oberpfalz',
                'land'    => 'Deutschland',
                'website' => 'www.lammsbraeu.de',
            ],
            'Lemonaid' => [
                'adresse' => 'Neuer Kamp 31',
                'plz'     => '20359',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'website' => 'www.lemon-aid.de',
            ],
            'Licher' => [
                'adresse' => 'Berliner Straße 2',
                'plz'     => '35423',
                'ort'     => 'Lich',
                'land'    => 'Deutschland',
                'website' => 'www.licher.de',
            ],
            'Licor 43' => [
                'adresse' => 'Ctra. de La Palma, 1',
                'plz'     => '30395',
                'ort'     => 'Cartagena',
                'land'    => 'Spanien',
                'website' => 'www.licor43.com',
            ],
            'loesch zwerg' => [
                'adresse' => 'Hauptstraße 16',
                'plz'     => '86459',
                'ort'     => 'Gessertshausen',
                'land'    => 'Deutschland',
                'website' => 'www.loesch-zwerg.de',
            ],
            'Loscher' => [
                'adresse' => 'Steigerwaldstraße 21-23',
                'plz'     => '91481',
                'ort'     => 'Münchsteinach',
                'land'    => 'Deutschland',
                'website' => 'www.brauerei-loscher.de',
            ],
            'Nestle' => [
                'adresse' => 'Lyoner Straße 23',
                'plz'     => '60528',
                'ort'     => 'Frankfurt am Main',
                'land'    => 'Deutschland',
                'website' => 'www.nestle.de',
            ],
            'Odenwaldquelle' => [
                'adresse' => 'Ludwigstraße 100',
                'plz'     => '64646',
                'ort'     => 'Heppenheim',
                'land'    => 'Deutschland',
                'website' => 'www.odenwaldquelle.de',
            ],
            'Paulaner Brauerei Gruppe GmbH & Co. KGaA' => [
                'adresse' => 'Ohlmüllerstraße 42',
                'plz'     => '81541',
                'ort'     => 'München',
                'land'    => 'Deutschland',
                'website' => 'www.paulaner.de',
            ],
            'PepsiCo' => [
                'adresse' => 'Hugenottenallee 173',
                'plz'     => '63263',
                'ort'     => 'Neu-Isenburg',
                'land'    => 'Deutschland',
                'website' => 'www.pepsico.de',
            ],
            'Pernod Ricard' => [
                'adresse' => 'Habsburgerring 2',
                'plz'     => '50674',
                'ort'     => 'Köln',
                'land'    => 'Deutschland',
                'website' => 'www.pernod-ricard.com',
            ],
            'Possmann' => [
                'adresse' => 'Eschborner Landstraße 156-162',
                'plz'     => '60489',
                'ort'     => 'Frankfurt am Main',
                'land'    => 'Deutschland',
                'website' => 'www.possmann.de',
            ],
            'Radeberger' => [
                'adresse' => 'Darmstädter Landstraße 185',
                'plz'     => '60598',
                'ort'     => 'Frankfurt am Main',
                'land'    => 'Deutschland',
                'website' => 'www.radeberger-gruppe.de',
            ],
            'Redbull' => [
                'adresse' => 'Am Brunnen 1',
                'plz'     => '5330',
                'ort'     => 'Fuschl am See',
                'land'    => 'Österreich',
                'website' => 'www.redbull.com',
            ],
            'Rothaus' => [
                'adresse' => 'Rothaus 1',
                'plz'     => '79865',
                'ort'     => 'Grafenhausen',
                'land'    => 'Deutschland',
                'website' => 'www.rothaus.de',
            ],
            'Rotkäppchen-Mumm Sektkellereien GmbH' => [
                'adresse' => 'Sektkellereistraße 5',
                'plz'     => '06632',
                'ort'     => 'Freyburg (Unstrut)',
                'land'    => 'Deutschland',
                'website' => 'www.rotkaeppchen-mumm.de',
            ],
            'Schweppes Deutschland GmbH' => [
                'adresse' => 'Hagener Straße 261',
                'plz'     => '57223',
                'ort'     => 'Kreuztal',
                'land'    => 'Deutschland',
                'website' => 'www.schweppes.de',
            ],
            'Sinalco' => [
                'adresse' => 'Römerstraße 109',
                'plz'     => '47179',
                'ort'     => 'Duisburg',
                'land'    => 'Deutschland',
                'website' => 'www.sinalco.de',
            ],
            'Spezi' => [
                'adresse' => 'Ohlmüllerstraße 42',
                'plz'     => '81541',
                'ort'     => 'München',
                'land'    => 'Deutschland',
                'website' => 'www.paulaner.de',
            ],
            'St. Leonhardsquellen' => [
                'adresse' => 'Mühlthalweg 54',
                'plz'     => '83071',
                'ort'     => 'Stephanskirchen',
                'land'    => 'Deutschland',
                'website' => 'www.st-leonhards-quellen.de',
            ],
            'Staatl Fachingen' => [
                'adresse' => 'Brunnenstraße 11',
                'plz'     => '65626',
                'ort'     => 'Birlenbach',
                'land'    => 'Deutschland',
                'website' => 'www.fachingen.de',
            ],
            'Stoertebeker' => [
                'adresse' => 'Greifswalder Chaussee 84-85',
                'plz'     => '18439',
                'ort'     => 'Stralsund',
                'land'    => 'Deutschland',
                'website' => 'www.stoertebeker.com',
            ],
            'Tegernseer' => [
                'adresse' => 'Schloßplatz 1',
                'plz'     => '83684',
                'ort'     => 'Tegernsee',
                'land'    => 'Deutschland',
                'website' => 'www.brauhaus-tegernsee.de',
            ],
            'Viva con agua' => [
                'adresse' => 'Meiendorfer Mühlenweg 119',
                'plz'     => '22159',
                'ort'     => 'Hamburg',
                'land'    => 'Deutschland',
                'website' => 'www.vivaconagua.org',
            ],
        ];

        foreach ($brands as $name => $data) {
            DB::table('brands')->where('name', $name)->update($data);
        }
    }

    public function down(): void
    {
        DB::table('brands')->update([
            'adresse' => null,
            'plz'     => null,
            'ort'     => null,
            'land'    => 'Deutschland',
            'email'   => null,
            'website' => null,
        ]);
    }
};
